/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import app.src.main.java.project.App;

class AppTest {
    
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
