/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    Logger log = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
